# Generated by Django 3.2.25 on 2024-11-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241118_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Верификация', 'verbose_name_plural': 'Верификация'},
        ),
    ]
